POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test_note",
    "number": "123-321"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "123-321"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test_note"
}

### Duplicated note
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test_note",
    "number": "123-321"
}